import {
  Activity,
  AirVent,
  AlarmSmoke,
  AlertTriangle,
  Ampersand,
  Anchor,
  Aperture,
  Archive,
  ArrowUpRight,
  BadgeCheck,
  BatteryCharging,
  Bell,
  Bike,
  Binoculars,
  Bluetooth,
  Bomb,
  Bookmark,
  Box,
  BrickWall,
  Building2,
  Cable,
  Calculator,
  Calendar,
  Camera,
  Car,
  Castle,
  CircuitBoard,
  CircleDot,
  ClipboardList,
  Clock,
  Cloud,
  Compass,
  Construction,
  Container,
  Cpu,
  Crosshair,
  Database,
  Disc3,
  DoorOpen,
  DraftingCompass,
  Droplets,
  Drill,
  Earth,
  Factory,
  Fan,
  FileText,
  Fingerprint,
  FireExtinguisher,
  Flag,
  Flame,
  Flashlight,
  FlaskConical,
  Fuel,
  Gauge,
  Gem,
  Globe,
  GraduationCap,
  Grid3x3,
  Hammer,
  Hand,
  HardHat,
  Headphones,
  Heart,
  HelpingHand,
  Hexagon,
  Home,
  Hospital,
  Hourglass,
  Image,
  Info,
  KeyRound,
  Landmark,
  Layers,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Link2,
  LocateFixed,
  Lock,
  Magnet,
  Map as MapIcon,
  MapPin,
  Megaphone,
  Microscope,
  Monitor,
  Mountain,
  Navigation,
  Network,
  Newspaper,
  Orbit,
  Package,
  Paintbrush,
  ParkingMeter,
  PencilRuler,
  PersonStanding,
  Phone,
  Pill,
  Pipette,
  Plane,
  Plug,
  Power,
  Printer,
  Puzzle,
  QrCode,
  Radio,
  Recycle,
  Refrigerator,
  Rocket,
  Route,
  Ruler,
  Satellite,
  Scale,
  ScanLine,
  Scissors,
  Server,
  Settings,
  Shield,
  Ship,
  ShoppingCart,
  Shovel,
  Signal,
  Siren,
  Snowflake,
  Sparkles,
  Speaker,
  SquareStack,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Tag,
  Target,
  Tent,
  Thermometer,
  Timer,
  ToolCase,
  TowerControl,
  TrainFront,
  Trash2,
  TreePine,
  Trophy,
  Truck,
  Unplug,
  Users,
  Utensils,
  Video,
  Volume2,
  Warehouse,
  Waves,
  Wifi,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type CategoryIconOption = {
  name: string;
  label: string;
  icon: LucideIcon;
};

/** Curated Lucide set for legend categories. `name` is stored on the category. */
export const CATEGORY_ICONS: CategoryIconOption[] = [
  { name: "Star", label: "Star", icon: Star },
  { name: "Shield", label: "Shield", icon: Shield },
  { name: "AlertTriangle", label: "Warning", icon: AlertTriangle },
  { name: "Info", label: "Info", icon: Info },
  { name: "Zap", label: "Bolt", icon: Zap },
  { name: "Settings", label: "Settings", icon: Settings },
  { name: "Wrench", label: "Wrench", icon: Wrench },
  { name: "Hammer", label: "Hammer", icon: Hammer },
  { name: "HardHat", label: "Hard hat", icon: HardHat },
  { name: "Construction", label: "Construction", icon: Construction },
  { name: "Factory", label: "Factory", icon: Factory },
  { name: "Warehouse", label: "Warehouse", icon: Warehouse },
  { name: "Cpu", label: "CPU", icon: Cpu },
  { name: "CircuitBoard", label: "Circuit", icon: CircuitBoard },
  { name: "Server", label: "Server", icon: Server },
  { name: "Database", label: "Database", icon: Database },
  { name: "Network", label: "Network", icon: Network },
  { name: "Wifi", label: "Wi‑Fi", icon: Wifi },
  { name: "Signal", label: "Signal", icon: Signal },
  { name: "Bluetooth", label: "Bluetooth", icon: Bluetooth },
  { name: "Gauge", label: "Gauge", icon: Gauge },
  { name: "Activity", label: "Activity", icon: Activity },
  { name: "Flame", label: "Flame", icon: Flame },
  { name: "FireExtinguisher", label: "Extinguisher", icon: FireExtinguisher },
  { name: "AlarmSmoke", label: "Smoke alarm", icon: AlarmSmoke },
  { name: "Siren", label: "Siren", icon: Siren },
  { name: "Droplets", label: "Droplets", icon: Droplets },
  { name: "Waves", label: "Waves", icon: Waves },
  { name: "Thermometer", label: "Temperature", icon: Thermometer },
  { name: "Snowflake", label: "Cold", icon: Snowflake },
  { name: "Sun", label: "Sun", icon: Sun },
  { name: "Wind", label: "Wind", icon: Wind },
  { name: "AirVent", label: "Vent", icon: AirVent },
  { name: "Fan", label: "Fan", icon: Fan },
  { name: "Leaf", label: "Leaf", icon: Leaf },
  { name: "Recycle", label: "Recycle", icon: Recycle },
  { name: "TreePine", label: "Tree", icon: TreePine },
  { name: "Mountain", label: "Mountain", icon: Mountain },
  { name: "Earth", label: "Earth", icon: Earth },
  { name: "Globe", label: "Globe", icon: Globe },
  { name: "Lightbulb", label: "Idea", icon: Lightbulb },
  { name: "Flashlight", label: "Flashlight", icon: Flashlight },
  { name: "Power", label: "Power", icon: Power },
  { name: "BatteryCharging", label: "Battery", icon: BatteryCharging },
  { name: "Plug", label: "Plug", icon: Plug },
  { name: "Unplug", label: "Unplug", icon: Unplug },
  { name: "Cable", label: "Cable", icon: Cable },
  { name: "Fuel", label: "Fuel", icon: Fuel },
  { name: "MapPin", label: "Location", icon: MapPin },
  { name: "LocateFixed", label: "Locate", icon: LocateFixed },
  { name: "Map", label: "Map", icon: MapIcon },
  { name: "Compass", label: "Compass", icon: Compass },
  { name: "Navigation", label: "Navigation", icon: Navigation },
  { name: "Route", label: "Route", icon: Route },
  { name: "Flag", label: "Flag", icon: Flag },
  { name: "Crosshair", label: "Crosshair", icon: Crosshair },
  { name: "Target", label: "Target", icon: Target },
  { name: "Truck", label: "Truck", icon: Truck },
  { name: "Car", label: "Car", icon: Car },
  { name: "Bike", label: "Bike", icon: Bike },
  { name: "TrainFront", label: "Train", icon: TrainFront },
  { name: "Plane", label: "Plane", icon: Plane },
  { name: "Ship", label: "Ship", icon: Ship },
  { name: "Rocket", label: "Rocket", icon: Rocket },
  { name: "Package", label: "Package", icon: Package },
  { name: "Box", label: "Box", icon: Box },
  { name: "Container", label: "Container", icon: Container },
  { name: "Archive", label: "Archive", icon: Archive },
  { name: "Layers", label: "Layers", icon: Layers },
  { name: "SquareStack", label: "Stack", icon: SquareStack },
  { name: "Grid3x3", label: "Grid", icon: Grid3x3 },
  { name: "Building2", label: "Building", icon: Building2 },
  { name: "Home", label: "Home", icon: Home },
  { name: "Castle", label: "Castle", icon: Castle },
  { name: "Landmark", label: "Landmark", icon: Landmark },
  { name: "DoorOpen", label: "Door", icon: DoorOpen },
  { name: "BrickWall", label: "Wall", icon: BrickWall },
  { name: "Tent", label: "Tent", icon: Tent },
  { name: "Anchor", label: "Anchor", icon: Anchor },
  { name: "Lock", label: "Lock", icon: Lock },
  { name: "KeyRound", label: "Key", icon: KeyRound },
  { name: "Fingerprint", label: "Fingerprint", icon: Fingerprint },
  { name: "ScanLine", label: "Scan", icon: ScanLine },
  { name: "QrCode", label: "QR code", icon: QrCode },
  { name: "Bell", label: "Bell", icon: Bell },
  { name: "Megaphone", label: "Megaphone", icon: Megaphone },
  { name: "Radio", label: "Radio", icon: Radio },
  { name: "Satellite", label: "Satellite", icon: Satellite },
  { name: "TowerControl", label: "Tower", icon: TowerControl },
  { name: "Orbit", label: "Orbit", icon: Orbit },
  { name: "Camera", label: "Camera", icon: Camera },
  { name: "Video", label: "Video", icon: Video },
  { name: "Aperture", label: "Aperture", icon: Aperture },
  { name: "Image", label: "Image", icon: Image },
  { name: "Binoculars", label: "Binoculars", icon: Binoculars },
  { name: "Monitor", label: "Monitor", icon: Monitor },
  { name: "Printer", label: "Printer", icon: Printer },
  { name: "Phone", label: "Phone", icon: Phone },
  { name: "Headphones", label: "Headphones", icon: Headphones },
  { name: "Speaker", label: "Speaker", icon: Speaker },
  { name: "Volume2", label: "Volume", icon: Volume2 },
  { name: "Microscope", label: "Microscope", icon: Microscope },
  { name: "FlaskConical", label: "Lab", icon: FlaskConical },
  { name: "Pipette", label: "Pipette", icon: Pipette },
  { name: "Pill", label: "Pill", icon: Pill },
  { name: "Syringe", label: "Syringe", icon: Syringe },
  { name: "Stethoscope", label: "Medical", icon: Stethoscope },
  { name: "Hospital", label: "Hospital", icon: Hospital },
  { name: "LifeBuoy", label: "Life buoy", icon: LifeBuoy },
  { name: "Hand", label: "Hand", icon: Hand },
  { name: "HelpingHand", label: "Help", icon: HelpingHand },
  { name: "PersonStanding", label: "Person", icon: PersonStanding },
  { name: "Users", label: "Team", icon: Users },
  { name: "GraduationCap", label: "Training", icon: GraduationCap },
  { name: "ClipboardList", label: "Checklist", icon: ClipboardList },
  { name: "FileText", label: "Document", icon: FileText },
  { name: "Newspaper", label: "News", icon: Newspaper },
  { name: "Calendar", label: "Calendar", icon: Calendar },
  { name: "Clock", label: "Clock", icon: Clock },
  { name: "Timer", label: "Timer", icon: Timer },
  { name: "Hourglass", label: "Hourglass", icon: Hourglass },
  { name: "Calculator", label: "Calculator", icon: Calculator },
  { name: "Scale", label: "Scale", icon: Scale },
  { name: "Ruler", label: "Ruler", icon: Ruler },
  { name: "PencilRuler", label: "Drafting", icon: PencilRuler },
  { name: "DraftingCompass", label: "Draft compass", icon: DraftingCompass },
  { name: "Paintbrush", label: "Brush", icon: Paintbrush },
  { name: "Scissors", label: "Scissors", icon: Scissors },
  { name: "Shovel", label: "Shovel", icon: Shovel },
  { name: "Drill", label: "Drill", icon: Drill },
  { name: "ToolCase", label: "Toolbox", icon: ToolCase },
  { name: "Magnet", label: "Magnet", icon: Magnet },
  { name: "Bomb", label: "Hazard", icon: Bomb },
  { name: "Link2", label: "Link", icon: Link2 },
  { name: "Tag", label: "Tag", icon: Tag },
  { name: "Bookmark", label: "Bookmark", icon: Bookmark },
  { name: "BadgeCheck", label: "Verified", icon: BadgeCheck },
  { name: "Trophy", label: "Trophy", icon: Trophy },
  { name: "Gem", label: "Gem", icon: Gem },
  { name: "Heart", label: "Heart", icon: Heart },
  { name: "Sparkles", label: "Sparkles", icon: Sparkles },
  { name: "Cloud", label: "Cloud", icon: Cloud },
  { name: "Disc3", label: "Disc", icon: Disc3 },
  { name: "Puzzle", label: "Puzzle", icon: Puzzle },
  { name: "Hexagon", label: "Hexagon", icon: Hexagon },
  { name: "CircleDot", label: "Dot", icon: CircleDot },
  { name: "ArrowUpRight", label: "External", icon: ArrowUpRight },
  { name: "ShoppingCart", label: "Cart", icon: ShoppingCart },
  { name: "Utensils", label: "Food", icon: Utensils },
  { name: "Refrigerator", label: "Fridge", icon: Refrigerator },
  { name: "ParkingMeter", label: "Parking", icon: ParkingMeter },
  { name: "Trash2", label: "Waste", icon: Trash2 },
  { name: "Ampersand", label: "And", icon: Ampersand },
];

const CATEGORY_ICON_MAP = new Map(
  CATEGORY_ICONS.map((item) => [item.name, item.icon] as const),
);

export const DEFAULT_CATEGORY_ICON = "Star";

export function getCategoryLucideIcon(name: string): LucideIcon {
  return CATEGORY_ICON_MAP.get(name) ?? Star;
}

/** Map legacy emoji icons (from earlier builds) to Lucide names. */
export function normalizeCategoryIcon(icon: string): string {
  const legacy: Record<string, string> = {
    "★": "Star",
    "ℹ": "Info",
    "⚠": "AlertTriangle",
    "⚙": "Settings",
    "⚡": "Zap",
    "✓": "BadgeCheck",
    "❓": "Info",
    "✋": "Hand",
    "↗": "ArrowUpRight",
  };
  if (legacy[icon]) return legacy[icon];
  if (CATEGORY_ICON_MAP.has(icon)) return icon;
  return DEFAULT_CATEGORY_ICON;
}
