# Verified LTS Node.js base image
FROM mcr.microsoft.com/devcontainers/javascript-node:20

# Run as non-root user 'node' so malicious scripts can't escalate host permissions
USER node

WORKDIR /workspaces/app